packages:
  - "packages/*"

catalog:
  "@jest/types": ^29.6.3
  "@types/jest": ^29.5.14
  "@types/node": ^22.14.1
  "@types/react": ^19.1.2
  clsx: ^2.1.1
  fast-xml-parser: ^5.2.0
  jest: ^29.7.0
  react: ^19.1.0
  react-dom: ^19.1.0
  ts-jest: ^29.3.2
  ts-node: ^10.9.2
  typescript: ^5.8.3
