name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version compatible with your project
          cache: "npm"

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests (optional, remove if not needed)
      - name: Run Tests
        run: npm test

      # Build the package
      - name: Build Package
        run: npm run build

      # Publish to NPM
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
